### ISSUE TITLE
Object With Array

### ISSUE THREAD

**Issue by cjbarth** [MortalFlesh/jasmine-data-provider#3]
Would you be interested in a PR that would allow better support of nested calls of this provider?

For example, something like:

```
var data = {
  "data1": {
    "subddata1": {
      "operation1": [
        "item1",
        "item2",
      ]
    }
  }
}
```

Right now, objects are processed by taking the `key` of an object, and appending it to the end of the `value`, which is converted to an array if it isn't already one. This would mean that for a given operation one wishes to perform over a set of items there is no way to get the name of the operation unless one jumps to the end of the list of items. Unfortunately, this all must be done using the `arguments` variable on a single `it` because the looping value of having an array is lost.

It would be nice to have a little logic in here that would properly iterate over a `value` that is an array and not just append the description to the end of the array.

I'm thinking something like this:

```
    return function (values, func) {
        if (values instanceof Function) {
            values = values();
        }

        if (values instanceof Array) {
            values.forEach(function(value) {
                if (!(value instanceof Array)) {
                    value = [value];
                }

                func.apply(this, value);
            });
        } else {
            var objectKeys = Object.keys(values);

            objectKeys.forEach(function(key) {
                if (values[key] instanceof Array) {
                    values[key].forEach(function(value) {
                        if (!(value instanceof Array)) {
                            value = [value];
                        }

                        value.push(key);

                        func.apply(this, value);
                    });
                } else {
                    values[key] = [values[key]];

                    values[key].push(key);

                    func.apply(this, values[key]);
                }
            });
        }
    };
```

**Comment by MortalFlesh** [comment]
Hello,

could you provide me a testcase of what you want it for?

I was trying to understand the reason, but I couldn't.

Objects in provider are for simple reason of having the dataset named (as it is in PHPunit).

``` javascript
describe('test addition', function () {
    function plusProvider() {
        return {
            '2+3 = 5': {exam: {a: 2, b: 3, operator: '+'}, expected: 5},
            '14+15 = 29': {exam: {a: '14', b: 15, operator: '+'}, expected: 29},
        };
    }

    using(plusProvider, function (data, datasetName) {
        it('should calc for dataset ' + datasetName, function () {
            var result = calculator.calc(data.exam);

            expect(result).toEqual(data.expected);
        });
    });
});
```

So if test fails, you can see which case failed by the `datasetName`.

So I don't know why would you need nested objects there. 
Or do I miss something?

Thanks

**Comment by cjbarth** [comment]
For example, instead of having a dozen different `using` blocks with a dozen different variables each with an array, one could imagine a block like:

```
var pathsToTest = {
  "apiPaths": [
    "/path1",
    "/path2"
  ],
  "debugPaths": {
    "/path3",
    "/path4"
  ]
}
```

With that data structure I can just have a single `using` block, pass it `pathsToTest` and it would pick up each `key`, pass it as the `description` and then test every item in the array. Currently that isn't possible as the key gets appended to the list of items in the array such that a single call in the form `("/path1", "/path2", "apiPaths")` is made instead of the desired two calls like `("/path1", "apiPaths")` and `("/path2", "apiPaths")`.

**Comment by MortalFlesh** [comment]
Well IMO your case is not valid.

It would deny the possibility to pass an array as a value to be provided.

Like in the next example. You have a Router method `fooCollection`, which accepts array as a parameter and maps that array to same array.

``` javascript
Router.prototype.fooCollection = function(paths) {
    return paths.map((path) => path);
};

describe('test router', function () {
    var pathsToTest = {
        "apiPaths": [
            "/path1",
            "/path2"
        ],
        "debugPaths": [
            "/path3",
            "/path4"
        ]
    };

    using(pathsToTest, function (data, datasetName) {
        it('should do something with ' + datasetName, function () {
            var result = router.fooCollection(data);

            expect(result).toEqual(data);
        });
    });
});
```

So you provide an array to be tested as whole.

I think your case would be better put this way:

``` javascript
var pathsToTest = {
    "apiPath 1": "/path1",
    "apiPath 2": "/path2",
    "debugPath 1": "/path1",
    "debugPath 2": "/path2"
};

describe('test router', function () {
    var pathsToTest = {
        "apiPath 1": {path: "/path1", expected: "..."},
        "apiPath 2": {path: "/path2", expected: "..."},
        "debugPath 1": {path: "/path1", expected: "..."},
        "debugPath 2": {path: "/path2", expected: "..."}
    };

    using(pathsToTest, function (data, datasetName) {
        it('should do something with ' + datasetName, function () {
            var result = router.foo(data.path);

            expect(result).toEqual(data.expected);
        });
    });
});
```

It will give you the result for every path with datasetName in each case.

I hope this clarifies my point of view.

It seems to me that you would like to missuse data provider for something else.

If you want, you still can iterate over some collection to dynamically calls using with dataprovider but I dont think this would look nice :)

``` javascript
describe('test router', function () {
    var pathsToTest = {
        "apiPaths": [
            "/path1",
            "/path2"
        ],
        "debugPaths": [
            "/path3",
            "/path4"
        ]
    };

    var testCases = Object.keys(pathsToTest);

    testCases.forEach(function (testCase) {
        var provider = pathsToTest[testCase];

        using(provider, function (data) {
            it('should do something with ' + testCase, function () {
                var result = router.foo(data);

                expect(result).toEqual(data);
            });
        });
    });

});
```

So what do you think?

**Comment by cjbarth** [comment]
I see your point. I was thinking how it would be a lot of extra information in the object to use "apiPath 1" and "debugPath 1" when really all that is needed is to show the path that actually failed; thus, "apiPath1" and "debugPath 1" would never actually be shown in the test results. The reason for the distinction between an 'api' path and a 'debug' path would be the coded needed to perform the test.

It seems that the preference for this scenario would be to simply have multiple variables.

**Comment by MortalFlesh** [comment]
Well I dont think I totally understand your scenario. Can you provide that test case? 

Maybe you or me are just missing something.

**Comment by cjbarth** [comment]
Sure. Let's say I have 10 routes that need testing covering 1 API, 5 should fail, 5 should pass. I thus need 10 tests, with two different test bodies. I have several options:
1. 10 different tests, with most of the code being duplicated 10 times.
2. 2 different tests, using this data provider, and two arrays, each of 5 items, one passed to each test, with most of the code being duplicated 2 times.
3. 2 different tests, using this data provider, and two objects, each of 5 items, one passed to each test, where the keys are 'route 1', 'route 2', etc. (they can't be 'pass', 'pass', ... 'fail', 'fail', because duplicate keys aren't allowed), and which are ignored in the test block because they add no value to the report or the test code, with most of the code being duplicated 2 times
4. 2 different tests, using a modified version of this data provider, and 1 object with 2 key:value pairs, where each key is the expected result ('pass', 'fail') and the value is the array of items to test for that result. There would only be one copy of the test code and it would take two arguments, the result and the route to test. It would then have a simple switch to assert with a `.not` or not

**Comment by MortalFlesh** [comment]
Well I hope I understand it correctly, so I would test this scenario somehow this way:

``` javascript
describe('test routing', function () {
    function routesProvider() {
        return {
            'route 1 - ok': {route: '/route-1-ok/', expected: 200},
            'route 2 - ok': {route: '/route-2-ok/', expected: 200},
            'route 3 - ok': {route: '/route-3-ok/', expected: 200},
            'route 4 - ok': {route: '/route-4-ok/', expected: 200},
            'route 5 - ok': {route: '/route-5-ok/', expected: 200},
            'route 1 - error': {route: '/route-1-error/', expected: 500},
            'route 2 - error': {route: '/route-2-error/', expected: 500},
            'route 3 - error': {route: '/route-3-error/', expected: 500},
            'route 4 - error': {route: '/route-4-error/', expected: 500},
            'route 5 - error': {route: '/route-5-error/', expected: 500},
        };
    }

    // using provider function which returns array
    using(routesProvider, function (data, datasetName) {
        it('should routes by dataset: ' + datasetName, function () {
            var result = router.routes(data.route);

            expect(result).toEqual(data.expected);
        });
    });
});
```

Im not sure how you determine if route is ok, so I simply used HTTP code (200-OK, 500-Error).

So you have `1 test` for `10 cases` (=`1 provider`) and IMHO thats it.
