### ISSUE TITLE
How to provide excel data in jasmine data provider

### ISSUE THREAD

**Issue by pankajkrdubey** [MortalFlesh/jasmine-data-provider#4]
This is the code that reads data from an excel column and return it:

```
/* Get Column Data and return */
this.getColumnData = function(FileName,SheetName,ColumnName)
{
    var ColumnDataList = new Array();
    var workbook = new Excel.Workbook(); 
    return workbook.xlsx.readFile(FileName).then(function() {
            var worksheet = workbook.getWorksheet(SheetName);
            for(var v=2;v<=worksheet.actualRowCount;v++)
            {
                ColumnDataList.push(worksheet.getCell(ColumnName+v).value);
            }
          return ColumnDataList;
        });     
};
```
Now this is my spec where I want to use the excel data as test data, how can I do it?

```
dataProvider([getColumnData('TestData.xlsx','Sheet1','A')], function(data){
        it('Search TC#1 - ISBN ', function(){
            nav.AccessSite();
            search.ISBN(data);
            element(by.buttonText('Product Details')).click();
            element(by.xpath(or.PDP.ISBN)).getText().then(function(isbn){
                expect(isbn).toContain(data);
            });
        });
```
Error message:

> Failed: each key must be a number of string; got undefined

The data that getColumnData returns are an array of data, which is this: `[ 9781405342704, 9780241186091, 9780241340189 ]`

**Comment by MortalFlesh** [comment]
Hello,
well as far as I can see on the first look, you are returning a promise from `getColumnData` function, not an array result directly.

So you need to do test (including provider) either in callback of promise or first store data in some variable and then test the result.

```javascript
// first option
getColumnData('TestData.xlsx','Sheet1','A').then(function(dataList) {
   dataProvider([dataList], function(data){
       it('Search TC#1 - ISBN ', function(){
            nav.AccessSite();
            search.ISBN(data);
            element(by.buttonText('Product Details')).click();
            element(by.xpath(or.PDP.ISBN)).getText().then(function(isbn){
                expect(isbn).toContain(data);
            });
   })
})
```
```javascript
// second option
var tmp = []
getColumnData('TestData.xlsx','Sheet1','A').then(function(dataList) {
    tmp.push(dataList)
})

dataProvider([tmp], function(data){
        it('Search TC#1 - ISBN ', function(){
            nav.AccessSite();
            search.ISBN(data);
            element(by.buttonText('Product Details')).click();
            element(by.xpath(or.PDP.ISBN)).getText().then(function(isbn){
                expect(isbn).toContain(data);
            });
        });
```

But in the end I dont see any problem with provider itself, it seems to be problem with your implementation.

I hope it helped.

**Comment by pankajkrdubey** [comment]
Hi, 
Thanks for the pointing out the issue with the implementation, I have corrected it. After correcting it I found a new challenge with the solutions, please have a look and help

Option#1: If I follow the option 1 then the error msg displays that **no spec found** which is understandable as may be the reason is that an **it** block can not be called inside a promise callback.

Option#2: This one seems the right approach and perhaps we are close to resolve it with this solution. **Issue:** As the **tmp** is an array in itself and when we call it inside the **dataProvider** then we have to pass it in **[ ]** which makes it **an array in an array**. Code:
```
dataProvider([tmp], function(data){
// body logic
}
```
so the actually data that is passed in dataProvider is this:
```
dataProvider([ [ 9781405342704, 9780241186091, 9780241340189 ] ], function(data){
// body logic
}
```
 so the error that script throws is :  

> Failed: each key must be a number of string; got undefined

When I directly pass the **temp** in dataProvider without using the **[ ]** , something like this:
```
dataProvider(tmp, function(data){
// body logic
}
```
then the error message that I get is 

> TypeError: Cannot convert undefined or null to object

**Comment by MortalFlesh** [comment]
Hello,
you shoul use array of objects in dataProvider, where Array determines usecases and object determines function arguments.

So it should be array of objects, like:
```javascript
var tmp = [
   {isbn: 9781405342704},
   {isbn: 9780241186091},
   {isbn: 9780241340189},
];

dataProvider(tmp, function(data){
    it('Search TC#1 - ISBN ', function(){
        nav.AccessSite();
        search.ISBN(data.isbn);
        element(by.buttonText('Product Details')).click();
        element(by.xpath(or.PDP.ISBN)).getText().then(function(isbn){
            expect(isbn).toContain(data.sbn);
        });
    });
});
```

and since your function will generate just isbn values, you can simply map them to the objects:
```javascript
var tmp = []
getColumnData('TestData.xlsx','Sheet1','A').then(function(dataList) {
    tmp.push(dataList)
})

dataProvider(tmp.map((isbn) => ({isbn})), function(data){
   // ...
})

```

and if you are not familiar with ES6, map could be done in the old way like this:
```javascript
dataProvider(tmp.map(function(isbn) { return {isbn: isbn} }), function(data){
   // ...
})
```

And that should be it :)

**Comment by pankajkrdubey** [comment]
Thanks Man, It works, really appreciate your help and support.
